using UnityEngine;

namespace VortexKarts.Data
{
    /// <summary>
    /// Tunable driving profile of a kart variant. Values are arcade-oriented, not physical.
    /// Default instances are generated by DefaultContent and saved into Resources/Data/Karts.
    /// </summary>
    [CreateAssetMenu(menuName = "Vortex Karts/Kart Stats", fileName = "KartStats")]
    public class KartStats : ScriptableObject
    {
        [Header("Identity")]
        public string id = "balanced";
        public string displayName = "Balanced";
        [TextArea] public string description = "";
        public int sortOrder = 0;

        [Header("Core stats")]
        [Tooltip("Top speed on asphalt, in metres per second.")]
        public float maxSpeed = 32f;
        [Tooltip("Forward acceleration in m/s^2 at low speed.")]
        public float acceleration = 14f;
        [Range(0f, 1f), Tooltip("Steering responsiveness and grip. 0 = truck, 1 = go-kart.")]
        public float handling = 0.5f;
        [Range(0f, 1f), Tooltip("How fast drift charge builds and how controllable the slide is.")]
        public float driftControl = 0.5f;
        [Tooltip("Mass used for collisions and knock-back. 100-260.")]
        public float weight = 160f;
        [Tooltip("Multiplier applied to every boost gained by this kart.")]
        public float boostPower = 1f;
        [Range(0.2f, 1f), Tooltip("Fraction of top speed kept while off-road.")]
        public float offRoadPenalty = 0.55f;

        [Header("Detailed tuning")]
        public float brakeDeceleration = 30f;
        public float reverseMaxSpeed = 11f;
        [Tooltip("Yaw rate in degrees per second at very low speed.")]
        public float steerRateLowSpeed = 120f;
        [Tooltip("Yaw rate in degrees per second at top speed.")]
        public float steerRateHighSpeed = 48f;
        [Tooltip("How quickly sideways velocity is removed (higher = grippier).")]
        public float grip = 9f;
        [Tooltip("Grip while drifting (lower = longer slides).")]
        public float driftGrip = 2.6f;
        [Tooltip("Extra yaw multiplier while drifting.")]
        public float driftSteerBonus = 1.35f;
        [Tooltip("Passive slowdown when not accelerating (m/s^2).")]
        public float coastDeceleration = 6f;

        [Header("Visuals")]
        public Color bodyColor = new Color(0.9f, 0.3f, 0.2f);
        public Color accentColor = new Color(0.95f, 0.85f, 0.2f);
        [Tooltip("Body length/width scale tweak per variant.")]
        public Vector3 bodyScale = Vector3.one;

        /// <summary>Yaw rate (deg/s) for a given speed fraction 0..1, scaled by handling.</summary>
        public float GetSteerRate(float speedFraction)
        {
            float f = Mathf.Pow(Mathf.Clamp01(speedFraction), 0.7f);
            float rate = Mathf.Lerp(steerRateLowSpeed, steerRateHighSpeed, f);
            return rate * Mathf.Lerp(0.8f, 1.25f, handling);
        }

        public float GetGrip(bool drifting)
        {
            float g = drifting ? driftGrip : grip;
            return g * Mathf.Lerp(0.85f, 1.2f, handling);
        }

        /// <summary>Seconds needed to reach each drift level, faster with better drift control.</summary>
        public float GetDriftChargeTime(int level)
        {
            float speed = Mathf.Lerp(1.25f, 0.8f, driftControl);
            switch (level)
            {
                case 1: return 0.9f * speed;
                case 2: return 1.9f * speed;
                default: return 3.0f * speed;
            }
        }

        public float MassForPhysics => Mathf.Clamp(weight, 60f, 400f);
    }
}
